### ISSUE TITLE
Algomorph issues with polyphony, inconsistent volume levels

### ISSUE THREAD

**Issue by forever-withyou** [anlexmatos/FM-Delexander#29]
Hello, 
mind you I'm pretty new to VCV rack overall I'm not 100% certain whether I'm doing everything correctly or whether maybe its issue with something else within rack rather than module itself, however from what I was able to test and reproduce, it all points to this module.

So, basically when I was playing with algomorph, using it as simple FM mod/algorithm router I realized that volume levels at times were way too low, then I play note again and its fine again.

![Rack_hXq44YcMNW](https://user-images.githubusercontent.com/28648242/178366127-e653741e-bd2a-444a-a239-3c885e44dddb.png)
ch2 is from algomorph, ch3-c6 are fed straight from FM-OPs

After some investigations I realized that some poly channels being output from "CARRIER SUM OUTPUT" end up being "poisoned" and they stay that way, always outputting too low volume.

Best way to reproduce it is set MIDI-CV module poly-mode as rotate and keep repeating some note until it happens.

![Rack_uIrYURtDm2](https://user-images.githubusercontent.com/28648242/178366809-65c421ce-b90f-4bc8-b79e-0e20b6973da0.png)

![Rack_po8vZtkZs0](https://user-images.githubusercontent.com/28648242/178367595-86678c8d-ae60-4e7d-94e5-8c447aad0d5f.png)

Here is most clear example I could think of on how to picture it (even though it looks like spaghetti lol) - mixmaster ch1-8, are split from CARRIER SUM, while ch9-16 are split straight from VCA (carrier's) levels throughout channels coming from Algomorph are random, ch2 was only one that was giving me correct levels, rest was losing volume some more than others but ch8 was critically low.

I tested it with 2 algomorphs, one hooked with bogaudio FM-OPs and other with VCV VCOs, it was happening with both, however volume distribution throughout channels was different for both cases.

![Rack_qrdq9nXhtN](https://user-images.githubusercontent.com/28648242/178368607-3ba9d257-63e2-4f5f-a9ae-a32f9b61736e.png)
![Rack_SWhWMG74T9](https://user-images.githubusercontent.com/28648242/178368684-5f3dc9d9-e83a-4d2a-9f00-48298b0fe33e.png)

Algomorphs, were on default init settings, other than setting algorithm - untouched. After I realized it's happening I tried to change audio -> average sum output, however it didn't seem to help with anything.

Anyway I still quietly hope that someone tells me I'm doing something wrong, however I think there is something happening here...

Anyhow, amazing module, thank you for making it.

**Comment by xandramax** [comment]
Thanks for the report and the kind words! I'm excited to hear that someone using Algomorph polyphonically, especially someone with an MPE controller. I've been waiting quite a while for an Osmose from Expressive E so that I can better explore this use case myself.

I've been playing around a bit looking into your issue, and I think what might be going on here is something to do with VCO phase and destructive interference. I think that the phases of different channels of any single oscillator are not in sync, and that's why the inconsistency in volume levels shows up.

In order to test this theory, one thing you can do is to try replacing Algomorph with direct FM cabling between your oscillators and a simple mixer for the carriers. I think you will find that the relative volume levels for each channel are the same as when using Algomorph.

If this is indeed the case, here are some things you could do in your patch to help eliminate (or homogenize) any interference:
- Increase the setting of the FM depth knob on Operator 1 in the FM-OP patch that you shared. This will make sure that the outputs of Operator 1 and 4 are very different even though they have the same frequency
- Or, change the frequency of one or more operators so that no two are the same
- Or, make use of the Sync input if your VCO has one (Bogaudio "VCO" does but "FM-OP" doesn't) in order to take more direct control over your operators' phases across all channels. This way you should be able to ensure that any interference is consistent, in case it's an intentional effect that you're looking to utilize

If I'm off the mark here and you're still having trouble, please let me know.

**Comment by forever-withyou** [comment]
Heh, me being greenhorn had shown right here

I think you are correct actually, phase cancel explains it perfectly wow ... I was so mesmerized by this happening consistently on same channels every time that I forgot basics. 

Today I loaded "bugged project state" from yday and surprise ... it wasn't happening at all... phases were not syncing at all after loading. What I did was ctrl+d carrier 1 and replace carrier 4 with cloned dupe of 1 (even though their settings were already same on init state) - voila syncing again and was happening consistently on same of channels like yday. So I tested with simple unity mixer, of course it's happening...

I'm still confused how can they sync consistently only on some channels and never on others but it must be some internal VCV things I guess, almost as if phase had a seed.

Heh if I pressed on and finish my intended algos I would never notice it because carriers wouldn't be so close to each other, now that I think about it all was so stupid...

Thank you ^^

**Comment by xandramax** [comment]
Glad to hear it worked! Don't be too hard on yourself; I've run into a lot of stuff like this that left me scratching my head while testing and developing. And like you said, the way it plays out across polyphony channels is confusing and not obvious.

Don't hesitate to reach out with any other questions!
