### ISSUE TITLE
Display can't handle 4-OP algorithm with feedback

### ISSUE THREAD

**Issue by zezic** [anlexmatos/FM-Delexander#5]
When building a **feedback** algorithm **with all 4 operators** involved the display shows its initial state and just displays 1 2 3 4 in a row without any graph arrows.

For example, the next algorithm is displayed correctly (I got arrows on the screen):
```
1 -> 2
2 -> 3
3 -> 1
```

But this algorithm is not visualized:
```
1 -> 2
2 -> 3
3 -> 4
4 -> 1
```

**Comment by anlexmatos** [comment]
The screen's visualization has been designed under the assumption that all algorithms will have at least one clear carrier (i.e. at least one carrier that is not modulating another operator via Algomorph).

Unfortunately, when you account for the possibility that all operators may be modulators at the same time, the number of possible graphs which need to be visualized balloons from 1695 to 65,536. Currently all of the algorithm visualizations are hard-coded (enumerated in dot language, rendered to SVG, coordinate information extracted by Beautiful Soup to CSV, then stored directly in arrays [here](https://github.com/anlexmatos/FM-Delexander/blob/master/src/GraphData.hpp)). In the future I'm planning to further investigate dynamically generating the visualizations in the interest of building 6 and 8 operator versions of Algomorph, and if that pans out then I'll also be able to add support for visualizing algorithms like you've described.

The current general design of the module (both audio and visual) assumes that any feedback will involve an operator directly modulating itself, and therefore can (should?) be handled using the feedback knob on the operator module itself. I am planning on providing an alternate mode in which horizontal connections are possible. Currently, "horizontal connections" are used as a means of disabling an operator. (This is why the line comes up red. I'm just beginning to work on a manual, then I will publish the module on the Rack Library...) This should open up some interesting possibilities outside the core FM use-case, for example in situations where Algomorph's modulation outputs are not actually connected back to whatever is on the other side.

For the audio of the algorithm you've described, the appropriate routing is performed at least, although because there is no clear carrier the Sum output of Algomorph will be silent and "monitoring" of the algorithm will have to be done by hand. This would also affect an algorithm like:
1 -> 2
2 -> 3
3 -> 1
4
Here, all that would be heard from the Sum output would be operator 4. Maybe I can implement a mode where users can explicitly mark certain operators as carriers, forcing them to be copied to the Sum output even if they are also modulators.

The "all carriers" algorithm with no graph arrows is currently being used as a default (error) display. I think I should add an alternate visualization, like a big question mark, when the module does not know what should be shown on the screen.

Thank you for making me think about this more!

**Comment by zezic** [comment]
Wow, I didn't even think you were using pre-computed data. This fact led me to the articles about graph planarity testing, that's interesting...

**Comment by anlexmatos** [comment]
When I started working on the project, without much idea of how I'd actually be able to implement the screen, I found my way to the nauty/traces project for generating automorphism groups, and was trying to work off of that for a while. Eventually I realized that the set of graphs which I was most interested in was small enough, and dot language was simple enough, that it took surprisingly little time to just enumerate the whole set including isomorphs.

Coming across Beautiful Soup was a great moment, because by that point I already had 1695 SVG files and was just hoping it wouldn't be too hard to wrangle them into something usable. I've been meaning to upload that python script I wrote. As someone who had never worked with any sort of data processing of this sort before, and minimal experience with python, I found it surprisingly easy to work with.

**Comment by anlexmatos** [comment]
I've now implemented a much clearer "error display" to increase clarity when Algomorph is unable to visualize the current algorithm.
It is also now possible for users to forcibly designate any operator as a carrier, so that operators can act as modulators and carriers at the same time.
There's also now an alternate operating mode which allows for horizontal connections, and also in this mode the module does not perform any automatic carrier assignment.
Finally I've added 285 more graphs, corresponding to algorithms with 1, 2, or 3 operators. This means that when an operator is disabled, this is now clearly reflected in the display.

All of these changes can currently be found on the Beta 3 branch. Soon I'll be merging to master and releasing new test builds on the forum.
